apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns:secret-reader
  namespace: cert-manager
rules:
- apiGroups:
  - ""
  resourceNames:
  - duckdns-token
  resources:
  - secrets
  verbs:
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns:domain-solver
rules:
- apiGroups:
  - zb17.duckdns.org
  resources:
  - '*'
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-duckdns:secret-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns:webhook-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns:domain-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-duckdns:domain-solver
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    release: cert-manager-webhook-duckdns
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  replicas: null
  selector:
    matchLabels:
      app: cert-manager-webhook-duckdns
      app.zb/name: cert-manager-webhook-duckdns
      release: cert-manager-webhook-duckdns
  template:
    metadata:
      labels:
        app: cert-manager-webhook-duckdns
        app.zb/name: cert-manager-webhook-duckdns
        release: cert-manager-webhook-duckdns
    spec:
      containers:
      - args:
        - --tls-cert-file=/tls/tls.crt
        - --tls-private-key-file=/tls/tls.key
        - --v=2
        env:
        - name: GROUP_NAME
          value: zb17.duckdns.org
        image: ebrianne/cert-manager-webhook-duckdns:v1.2.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
        name: cert-manager-webhook-duckdns
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /tls
          name: certs
          readOnly: true
      serviceAccountName: cert-manager-webhook-duckdns
      volumes:
      - name: certs
        secret:
          secretName: cert-manager-webhook-duckdns-webhook-tls
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/cert-manager-webhook-duckdns-webhook-tls
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: v1alpha1.zb17.duckdns.org
spec:
  group: zb17.duckdns.org
  groupPriorityMinimum: 1000
  service:
    name: cert-manager-webhook-duckdns
    namespace: cert-manager
  version: v1alpha1
  versionPriority: 15
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app.zb/name: cert-manager-webhook-duckdns
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCbljnuD1IoprWrwAFcQDAgTkEariw+oAUvAk3mUH4aB24irQiXdB1pPjz7vGuX7S4C+vMftQ3RiIB60Rlas1ubuG67MhOIuuEhV4bhAWrKvW9G7SVuyhrz1avyfpFdtiqC+p9ug2jH0a6hWgCe7Cqnisy69qBmD2S5yn/XwWpCJ2gNY+3mSeGkJU6SK8iy6gbRkx1DqsQ2gyPp51KsvqNCh0VFnmwUniBAcgx+G3EOK0Ujr/ZHpp8+El3OlHO2sKHMfh9oJiGsrds6pExfHB2BGPglb4z2H8SzLMpsq6xAAUmSk/3N7IvUnGcJkLwxFngx02OTUIMq/VBG0R779wt738aGcPvKUrH5o0JZJxUx5TlAH3fK/kTBz6yVwPoFmCvT9d57f4QRgR4hyLxOZ+bcLGkY9BrtFGMlIEWj3MXjPKw2KUfYMZ+AyWy2MbZVNVmNi95of01+CIA9hzAABpN/KgE0RD1siXP8O6jQqiFXnlicb6QeyCNmRHvgFnjPDpx3+I1Z94E1xxaiCoJj+4e1EbNXWa/7S4SNv/ZLazbGFHHE0hU3SVJtQQv6Z+ap0hfbYmDAvRsoe3ozNXLzqqPNv6lgXsXgtN8XcxKdI1z3NuCqj0pzNUa5qZpF0JD3QwoOf5XM4ZE8VT3kZx0qHMzSJ85GOMjGBh/F3gLAbWAnL4ugCR6K31uh4KzsaxUOZ6RC2205GZ/wHITi0Ug7cUvrLVoNG0T6w8uL/qQWdn2Zn1y5PdQ=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns-ca
  namespace: cert-manager
spec:
  commonName: ca.cert-manager-webhook-duckdns.cert-manager
  duration: 43800h0m0s
  isCA: true
  issuerRef:
    name: cert-manager-webhook-duckdns-selfsign
  secretName: cert-manager-webhook-duckdns-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns-webhook-tls
  namespace: cert-manager
spec:
  dnsNames:
  - cert-manager-webhook-duckdns
  - cert-manager-webhook-duckdns.cert-manager
  - cert-manager-webhook-duckdns.cert-manager.svc
  duration: 8760h0m0s
  issuerRef:
    name: cert-manager-webhook-duckdns-ca
  secretName: cert-manager-webhook-duckdns-webhook-tls
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns-production
spec:
  acme:
    email: zachary.e.bialik@gmail.com
    preferredChain: ISRG Root X1
    privateKeySecretRef:
      name: cert-manager-webhook-duckdns-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            apiTokenSecretRef:
              key: token
              name: duckdns-token
          groupName: zb17.duckdns.org
          solverName: duckdns
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns-ca
  namespace: cert-manager
spec:
  ca:
    secretName: cert-manager-webhook-duckdns-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    app.zb/name: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns
  name: cert-manager-webhook-duckdns-selfsign
  namespace: cert-manager
spec:
  selfSigned: {}
